package com.example.sample.controller;


import com.example.sample.model.User;
import com.example.sample.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping(path = "/user")
public class UserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(path = "/add")
    public @ResponseBody String addNewUser (@RequestParam String name,
                                            @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User(name, email);
        userRepository.save(n);
        return "saved!";
    }

    //@RequestMapping(value = "/all", method = RequestMethod.GET) - full code
    @GetMapping(path = "/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        return userRepository.findAll();
    }

    @GetMapping(path = "/get")
    public @ResponseBody Iterable<User> getByName(@RequestParam String name) {
        return userRepository.findByName(name);
    }




}
