version: '2.1'

services:
  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_TEST_NAME}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    container_name: mysql-server
